### ISSUE TITLE
v1.1 Goal

### ISSUE THREAD

**Issue by sivchari** [sivchari/gotwtr#108]
### OAuth

- [x] Generate Bearer Token

### Tweet
- [x] Manage Tweets
  - [x] Post a Tweet
  - [x] Delete a Tweet
- [x] Search Tweets
  - [x] Search the full archive of Tweets (Academic Research product track)
 - [x] Tweet Counts
   - [x] Receive a count of Tweets that match a query (Academic Research product track)
 - [x] Retweets
   - [x] Allows a user ID to Retweet a Tweet
   - [x] Allows a user ID to undo a Retweet
 - [x] Likes
   - [x] Allows a user ID  to like a Tweet
   - [x] Allows a user ID to unlike a Tweet
 - [x] #143
 
### Lists
 - [x] Manage List
   - [x] Creates a new List on behalf of an authenticated user
   - [x] Deletes a List the authenticated user owns
   - [x] Updates the metadata a List the authenticated user owns
 - [x] List members
   - [x] Add a member to a List that the authenticated user owns
   - [x] Removes a member from a List the authenticated user owns
 - [x] #133 
   - [x] Follows a List on behalf of an authenticated user
   - [x] Unfollows a List on behalf of an authenticated user
 - [x] #134
   - [x] Returns the pinned Lists of the authenticated user
   - [x] Pins a List on behalf of an authenticated user
   - [x] Unpins a List on behalf of an authenticated user

### Users   
- [x] Follows
  - [x] Allows a user ID to follow another user
  - [x] Allows a user ID to unfollow another user
- [x] Blocks
  - [x] Returns a list of users who are blocked by the specified user ID
  - [x] Allows a user ID to block another user
  - [x] Allows a user ID to unblock another user
- [x] Mutes
  - [x] Returns a list of users who are muted by the specified user ID
  - [x] Allows a user ID to mute another user
  - [x] Allows a user ID to unmute another user

### Batch compliance

- [x] #128
- [x] #129
- [x] #130

**Comment by sivchari** [comment]
In additional, we added book mark API.

**Comment by sivchari** [comment]
Thanks ! @mmmommm @thinca @kazdevl @senk8

**Comment by thinca** [comment]
@sivchari :tada:
BTW, did you forget to push the tag for v1.1?

**Comment by sivchari** [comment]
@thinca 
I know. I'm creating release description. Thanks 😄
