### ISSUE TITLE
Should we implement covid19-stream ?

### ISSUE THREAD

**Issue by sivchari** [sivchari/gotwtr#132]
Twitter provides new API [covid19-stream](https://developer.twitter.com/en/docs/api-reference-index). I'm annoying to should implement these. This API may be deprecated in the future (I hope it). As a result, If library user use these API, the user library isn't working. Of cource we can keep these API , but  I worry about if it's good way. What do you think ?

**Comment by sivchari** [comment]
cc @mmmommm @thinca

**Comment by thinca** [comment]
I have no plan to use that API.
It does not need for me.

**Comment by sivchari** [comment]
OK, I close this issue for this API is ambiguous if it's necessary or not.
